name: Go API Test Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: true
    
    - name: Install dependencies
      run: go mod download

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --out-format=colored-line-number

    - name: Run Tests
      run: go test -v ./... -coverprofile=coverage.txt

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.txt

    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report/test_report.html

    - name: Build
      run: go build -v ./...